# Version Docker Compose
# version: '3.8'
services:
  imaging:
    build: .
    image: imaging
    container_name: imaging
    stdin_open: true  # -i equivalent
    tty: true         # -t equivalent
    environment:
      - TZ=America/Lima
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/david/Documents/DATA:/opt/DATA
      - /home/david/Documents/DATA-2:/opt/DATA-2
      - /home/david/Documents/DATA-3:/opt/DATA-3
#      - /home/david/Documents/imaging/Imaging:/root/Imaging
    sysctls:
      - kernel.shmmax=3593184000
      - kernel.shmall=3593184000
    command: /bin/bash
